version: '3'

services:

  vsql:
    image: blackflysolutions/mariadb:10.1
    expose:
           - "3306"
    volumes:
      - vdb:/var/lib/mysql
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
   
  vhttp:
    image: blackflysolutions/drupal:7-apache-civicrm-5-stable
    domainname: ${VSITE_DOMAIN}
    expose:
           - "80"
    volumes:
      - vsite:/var/www/html/sites/default
    environment:
      - VSITE
      - VSITE_SITE
      - VSITE_DOMAIN
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - DRUPAL_DATABASE
      - CIVICRM_DATABASE
    depends_on:
      - vsql

  admin:
    # create a new, empty site at this location
    # build a temporary super-set of the vhttp container above, run some scripts, and then (maybe) exit.
    image: blackflysolutions/simuliidae-admin:7-apache-civicrm-5-stable
    #image: simuliidae_admin:latest
    #build:
    #  context: admin
    volumes:
      - vsite:/var/www/html/sites/default
    environment:
      - VSITE
      - VSITE_SITE
      - VSITE_SITE_NAME
      - VSITE_DOMAIN
      - VSITE_CIVICRM_VER
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - DRUPAL_DATABASE
      - CIVICRM_DATABASE
      - VSITE_NAME
      - VSITE_ADMIN_NAME
      - VSITE_ADMIN_MAIL
      - VSITE_USER_NAME
      - VSITE_USER_MAIL
      - VSITE_USER_ROLE
      - VSITE_FEATURE
      - VSITE_THEME

    depends_on:
      - vsql
      - vhttp

volumes:
    vsite:
    vdb:
